### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by tovade** [CTK-WARRIOR/GitCord#1]
Hi there! 👋 

Im using this package for my discord server.
But it keeps saying 403.
![image](https://user-images.githubusercontent.com/66245404/117853594-e7409d80-b288-11eb-9c3c-df22a34125e6.png)
Any idea why? 
Thanks

**Comment by CTK-WARRIOR** [comment]
Are you using gitall option?

**Comment by tovade** [comment]
No

**Comment by tovade** [comment]
i only added 3 repositories it needs notifications of

**Comment by CTK-WARRIOR** [comment]
The package was working before?

**Comment by tovade** [comment]
yes

**Comment by CTK-WARRIOR** [comment]
Did you provide the token, because it is necessary as GitHub provide 60 req/hour without token.

**Comment by tovade** [comment]
it was inactive for 6h then my friend did a commit then it showed that error

**Comment by CTK-WARRIOR** [comment]
Its better to provide the Github Token, so i suggest you use tokken.

**Comment by tovade** [comment]
its kinda annoying cuz im tracking my friends repo's to :/

**Comment by tovade** [comment]
welp ima try ask if he wants to give
